apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-340518
  artifacts:
    # - image: us.gcr.io/ticketing-dev-340518/auth
    - image: daviesesiro/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: daviesesiro/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: daviesesiro/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: daviesesiro/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
deploy:
  kubectl:
    manifests:
      - infra/k8s/*
