name: Payment Service Tests

on:
  pull_request:
    paths:
      - "payments/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: cd payments && npm install && yarn
        env:
          PAYSTACK_KEY: ${{ secrets.PAYSTACK_KEY }}
#  TODO change to payemts
