name: Orders Service Tests

on:
  pull_request:
    paths:
      - "orders/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: cd orders && npm install && yarn test
